baseURL: https://mprimi.github.io/rholodex/
languageCode: en-US
title: Rholodex
theme: photophobia

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 5

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

params:
  favicon: null
  site_logo: null
  description: Decentralized address book and contact managment system
  recent_posts_number: 10
